kind: DataGrid
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-page-datagrid
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    prefix: compositions-datagrid-filters
    asGrid: true
    items: []
  widgetDataTemplate:
    - forPath: items
      expression: >
        ${ [ .compositionspanels[] | { resourceRefId: .metadata.name, size: 24 } ] }
  resourcesRefs: []
  resourcesRefsTemplate:
    - iterator: ${ .compositionspanels }
      template:
        id: ${ .metadata.name }
        apiVersion: ${ .apiVersion }
        resource: panels
        namespace: ${ .metadata.namespace }
        name: ${ .metadata.name }
        verb: GET