kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-page-datagrid-button-drawer-filters
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    prefix: compositions-datagrid-filters
    fields:
      - label: Composition Name
        name: title
        type: string
      - label: Composition Status
        name: headerRight
        type: string
      - label: Composition Date
        name: headerLeft
        type: daterange
      - label: Composition Tags
        name: tags
        type: string