kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-page-datagrid-button-drawer-filters
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    prefix: compositions-datagrid-filters
    fields:
      - label: Name
        name: 
        - title
        type: string
      - label: Status
        name: 
        - headerLeft
        type: string
      - label: Date
        name: 
        - headerRight
        type: daterange
      - label: Tags
        name: 
        - tags
        type: string