kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-blueprints
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    resourceRefId: blueprints-page
    label: Blueprints
    icon: fa-rectangle-list
    path: /blueprints
    order: 20
  resourcesRefs:
    - id: blueprints-page
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: blueprints-page
      namespace: {{ .Release.Namespace }}
      resource: pages
      verb: GET