kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: templates-page
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    items:
      - resourceRefId: templates-row
  resourcesRefs:
    - id: templates-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: templates-row
      namespace: {{ .Release.Namespace }}
      resource: rows
      verb: GET