kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: blueprints-page
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    items:
      - resourceRefId: blueprints-row
  resourcesRefs:
    - id: blueprints-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: blueprints-row
      namespace: {{ .Release.Namespace }}
      resource: rows
      verb: GET