kind: RoutesLoader
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: routes-loader
  namespace: {{ .Release.Namespace }}
spec:
  widgetData: {}
  resourcesRefs: []
  resourcesRefsTemplate:
    - iterator: ${ .routes }
      template:
        id: ${ .metadata.namespace + "_" + .metadata.name }
        name: ${ .metadata.name }
        apiVersion: ${ .apiVersion }
        resource: routes
        namespace: ${ .metadata.namespace }
        verb: GET
  apiRef:
    name: all-routes
    namespace: {{ .Release.Namespace }}