kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-tablist-route
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    path: /compositions/{namespace}/{name}
    resourceRefId: composition-tablist
  resourcesRefs:
    - id: composition-tablist
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: "{name}-composition-tablist"
      namespace: "{namespace}"
      resource: tablists
      verb: GET
  